apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: postgres
  name: postgres
spec: 
  ports:
    - port: 3306
  selector: 
    name: postgres
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels: 
    name: postgres
spec: 
  containers: 
    - image: postgres
      name: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: secret
        - name: POSTGRES_USER
          value: redmine
      ports: 
        - containerPort: 3306
          name: postgres
      volumeMounts:
        - name: postgres_data
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres_data
      emptyDir: {}
