apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: redminefrontend
  name: redminefrontend
spec: 
  ports:
    - port: 80
  selector: 
    name: redmine
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: redmine
  labels: 
    name: redmine
spec: 
  containers: 
    - image: redmine
      name: redmine
      env:
        - name: POSTGRES_PORT_5432_TCP
          value: postgres
        - name: POSTGRES_ENV_POSTGRES_USER
          value: redmine
        - name: POSTGRES_ENV_POSTGRES_PASSWORD
          value: secret
        - name: POSTGRES_ENV_POSTGRES_DB
          value: redmine
      ports: 
        - containerPort: 3000
          name: wordpress
      volumeMounts:
        - name: redmine_data
          mountPath: /usr/src/redmine/files
  volumes:
    - name: redmine_data
      emptyDir: {}
